version: "3.8"

services:
  mysql-lms:
    image: mysql:8.0.12
    container_name: mysql-lms
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1151259363
    volumes:
      - "./mysql-lms/conf:/etc/mysql/conf.d"
      - "./mysql-lms/data:/var/lib/mysql"
      - "./mysql-lms/init:/docker-entrypoint-initdb.d"
    networks:
      - lms-net
  fastapi-lms:
    build: 
      context: ./fastapi-lms
      dockerfile: Dockerfile
    container_name: fastapi-lms
    ports:
      - "8080:8080"
    volumes:
      - ./fastapi-lms/cstery-lms:/cstery-lms  # 将本地代码挂载到容器内
    networks:
      - lms-net
    depends_on:
      - mysql-lms
  nginx-lms:
    image: nginx:alpine
    container_name: nginx-lms
    ports:
      - "5173:5173"
      - "5174:5174"
    volumes:
      - "./nginx-lms/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-lms/html:/usr/share/nginx/html"
    depends_on:
      - fastapi-lms
    networks:
      - lms-net
networks:
  lms-net:
    name: cstery-lms